mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("newsapp/", include("newsapp.urls")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsapp/urls.py
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from django.urls import path  # new

from . import views

app_name = "newsapp"

urlpatterns = [
    # ex: /newsapp/
    path("", views.index, name="index"),
    # ex: /newsapp/5/
    path("<int:article_id>/", views.detail, name="detail"),
    # ex: /newsapp/author=/
    path("author=<str:author_name_surname>/", views.author, name="author"),
    # ex: /newsapp/topic=/
    path("topic=<str:topic_name>/", views.topic, name="topic"),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/newsapp/models.py
"""
Change your models (in models.py).
Run python manage.py makemigrations to create migrations for those changes
Run python manage.py migrate to apply those changes to the database.
"""
from django import template
from django.db import models

register = template.Library()


# TODO: add possibility to add photos from (1) Google Storage and (2) local files \
# and a switch for them to be able to run locally and in cloud


class Author(models.Model):
    class NameSurname(models.TextChoices):
        JORDAN = "Jordan Price"
        IAN = "Ian Alvarez"
        WALLACE = "Wallace Castillo"
        KEN = "Ken Sanders"
        BOB = "Bob Patel"
        JAIME = "Jaime Myers"
        ELLA = "Ella Long"
        STACEY = "Stacey Ross"
        WILMA = "Wilma Foster"
        GINA = "Gina Jimenez"

    name_surname = models.CharField(
        max_length=100,
        choices=NameSurname.choices,
        default=NameSurname.JORDAN,
        primary_key=True,
    )

    def __str__(self):
        return self.name_surname


class Article(models.Model):
    headline = models.CharField(max_length=200)
    article_text = models.CharField(max_length=8000)
    image = models.ImageField(upload_to="images/")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100, default="economy")
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

    @classmethod
    def create(cls, headline, article_text, image, author, topic, pub_date):
        article = cls(
            headline=headline,
            article_text=article_text,
            image=image,
            author=author,
            topic=topic,
            pub_date=pub_date,
        )
        return article


if __name__ == "__main__":
    pass

newsapp/models.py
"""
Change your models (in models.py).
Run python manage.py makemigrations to create migrations for those changes
Run python manage.py migrate to apply those changes to the database.
"""
from django import template
from django.db import models

from src.config.config import load_config

register = template.Library()
config = load_config()

# TODO: add possibility to add photos from (1) Google Storage and (2) local files \
# and a switch for them to be able to run locally and in cloud


class Topic(models.Model):
    name = models.CharField(
        max_length=100,
        choices=[(topic, topic) for topic in config["django"]["topics"]],
        primary_key=True,
    )

    def __str__(self) -> str:
        return self.name


class Author(models.Model):
    name_surname = models.CharField(
        max_length=100,
        choices=[(author, author) for author in config["django"]["authors"]],
        primary_key=True,
    )

    image = models.ImageField(upload_to="images/authors/")

    def __str__(self):
        return self.name_surname


class Article(models.Model):
    headline = models.CharField(max_length=200)
    article_text = models.CharField(max_length=8000)
    image = models.ImageField(upload_to="images/")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

    @classmethod
    def create(cls, headline, article_text, image, author, topic, pub_date):
        article = cls(
            headline=headline,
            article_text=article_text,
            image=image,
            author=author,
            topic=topic,
            pub_date=pub_date,
        )
        return article

newsapp/views.py
import datetime

from django.shortcuts import get_object_or_404, render
from nltk.tokenize import sent_tokenize

from .models import Article, Author, Topic

NUM_OF_LATEST_NEWS = 6
NUM_OF_RECENTLY_ADDED = 7


def index(request):
    index_1 = NUM_OF_LATEST_NEWS
    index_2 = NUM_OF_LATEST_NEWS + NUM_OF_RECENTLY_ADDED
    latest_article_list = Article.objects.order_by("-pub_date")[:index_1]
    recently_added_article_list = Article.objects.order_by("-pub_date")[index_1:index_2]
    topic_list = Topic.objects.all()
    current_year = datetime.datetime.now().year
    context = {
        "latest_article_list": latest_article_list,
        "recently_added_article_list": recently_added_article_list,
        "topic_list": topic_list,
        "current_year": current_year,
        "current_year_3": current_year - 3,
    }
    return render(request, "newsapp/index.html", context)


def detail(request, article_id):
    index_1 = NUM_OF_LATEST_NEWS
    index_2 = NUM_OF_LATEST_NEWS + NUM_OF_RECENTLY_ADDED
    article = get_object_or_404(Article, pk=article_id)
    recently_added_article_list = Article.objects.exclude(
        headline=article.headline
    ).order_by("-pub_date")[index_1:index_2]
    article_text = [sentence for sentence in sent_tokenize(article.article_text)]
    topic_list = Topic.objects.all()
    current_year = datetime.datetime.now().year
    return render(
        request,
        "newsapp/detail.html",
        {
            "article": article,
            "article_text": article_text,
            "recently_added_article_list": recently_added_article_list,
            "topic_list": topic_list,
            "current_year": current_year,
            "current_year_3": current_year - 3,
        },
    )


def author(request, author_name_surname):
    index_1 = NUM_OF_LATEST_NEWS
    index_2 = NUM_OF_LATEST_NEWS + NUM_OF_RECENTLY_ADDED
    author_articles = Article.objects.filter(author=author_name_surname).order_by(
        "-pub_date"
    )
    author = get_object_or_404(Author, name_surname=author_name_surname)
    recently_added_article_list = Article.objects.exclude(
        author=author.name_surname
    ).order_by("-pub_date")[index_1:index_2]
    topic_list = Topic.objects.all()
    current_year = datetime.datetime.now().year
    return render(
        request,
        "newsapp/author.html",
        {
            "author_articles": author_articles,
            "recently_added_article_list": recently_added_article_list,
            "author_name_surname": author_name_surname,
            "author": author,
            "topic_list": topic_list,
            "current_year": current_year,
            "current_year_3": current_year - 3,
        },
    )


def topic(request, topic_name):
    index_1 = NUM_OF_LATEST_NEWS
    index_2 = NUM_OF_LATEST_NEWS + NUM_OF_RECENTLY_ADDED
    topic_articles = Article.objects.filter(topic=topic_name).order_by("-pub_date")
    topic = get_object_or_404(Topic, name=topic_name)
    recently_added_article_list = Article.objects.order_by("-pub_date")[index_1:index_2]
    topic_list = Topic.objects.all()
    current_year = datetime.datetime.now().year
    current_year_3 = datetime.datetime.now().year - 3
    return render(
        request,
        "newsapp/topic.html",
        {
            "topic_articles": topic_articles,
            "recently_added_article_list": recently_added_article_list,
            "topic_name": topic_name,
            "topic": topic,
            "topic_list": topic_list,
            "current_year": current_year,
            "current_year_3": current_year - 3,
        },
    )

mysite/newsapp/templates/newsapp/detail.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% load newsapp_extras %}
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>News Portal</title>
    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'newsapp/css/bootstrap.css' %}" />
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'newsapp/css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'newsapp/css/responsive.css' %}" rel="stylesheet" />
  </head>
  <body class="sub_page">
    <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="/newsapp/">
              <!-- <img src="static/newsapp/images/logo.png" alt=""> -->
              <img src="{% static 'newsapp/images/logo.png' %}" alt="My image">
              <span>
              News Portal
              </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                <ul class="navbar-nav  ">
                  <li class="nav-item active">
                    <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="about.html">About </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="service.html">Services </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="portfolio.html"> Portfolio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="news.html"> news </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="contact.html">Contact us</a>
                  </li>
                </ul>
              </div>
              <div class="quote_btn-container  d-flex justify-content-center">
                <a href="">
                <img src="{% static 'newsapp/images/call.png' %}" alt="">
                CALL : +01 1234567890
                </a>
                <a href="">
                <span>
                @
                </span>
                demo@gmail.com
                </a>
              </div>
              </div> -->
          </nav>
        </div>
      </header>
      <!-- end header section -->
    </div>
    <!-- TODO: add share on Fb, Whatsapp, Linkedin -->
    <!-- news section -->
    <main>
      <section class="news_section layout_padding">
        <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <div class="d-flex flex-column align-items-end">
              <!-- headline -->
              <div class="custom_heading-container">
                <h2>
                  {{ article.headline }}
                </h2>
              </div>
              <!-- image -->
              <div class="box">
                <div class="img-box article-image">
                  <a href="{% url 'newsapp:detail' article.id %}">
                  <img src="{{ article.image.url }}" alt="">
                  </a>
                </div>
              </div>
              <!-- subtitle -->
              <div class="subtitle-box">
                <p>Published: {{ article.pub_date|myDate }}</p>
                <p>Author: <a href="">{{ article.author }}</a></p>
                <div class="action-box">
                  <div class="action">
                    <!-- Whatspp -->
                    <a href="">
                    <img class="sm-icon" src="{% static 'newsapp/images/whatsapp.png' %}"  >
                    </a>
                    <!-- Facebook -->
                    <a href="">
                    <img class="sm-icon" src="{% static 'newsapp/images/facebook.png' %}"  >
                    </a>
                    <!-- Twitter -->
                    <a href="">
                    <img class="sm-icon" src="{% static 'newsapp/images/twitter-2.png' %}"  >
                    </a>
                    <!-- Whatsapp -->
                    <!-- Email -->
                    <a class="social-share__share" href="mailto:?subject=NewsPortal%20content%20share&amp;body=Check%20out%20this%20article%3A%0Ahttps%3A%2F%2Fwww.newsportal.com%2F2023%2F09%2F19%2Fchina%2Fchina-germany-xi-dictator-intl-hnk" data-type="email" target="_blank" rel="noopener noreferrer" aria-label="share with email" title="Share with email"></a>
                    <a href="">
                    <img class="sm-icon" src="{% static 'newsapp/images/mail.png' %}"  >
                    </a>
                    <!-- Link -->
                    <a href="">
                    <img class="sm-icon" src="{% static 'newsapp/images/link-2.png' %}"  >
                    </a>
                  </div>
                </div>
              </div>
              <!-- article -->
              <p>{{ article.article_text }}</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="container">
              <div class="row">
                <div class="col-sm-12">
                  <div class="d-flex flex-column align-items-end">
                    <div class="custom_heading-container">
                      <h3>
                        May also interest you
                      </h3>
                      <br>
                      <br>
                      <br>
                    </div>
                  </div>
                  <div>
                    <!-- add advert here -->
                  </div>
                  <div>
                    <!-- <div class="col-sm-12"> -->
                    {% for recent_article in recently_added_article_list %}
                    <div class="recent-news-box">
                      <div class="detail-box">
                        <h6>
                          <a href="{% url 'newsapp:detail' article.id %}">
                          {{ recent_article.headline }}
                          </a>
                        </h6>
                        <hr>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
    <!-- info section -->
    <footer>
      <section class="info_section layout_padding">
        <div class="container">
          <div class="info_social">
            <div>
              <a href="">
              <img src="{% static '/newsapp/images/fb.png' %}" alt="">
              </a>
            </div>
            <div>
              <a href="">
              <img src="{% static '/newsapp/images/twitter.png' %}" alt="">
              </a>
            </div>
            <div>
              <a href="">
              <img src="{% static '/newsapp/images/linkedin.png' %}" alt="">
              </a>
            </div>
            <div>
              <a href="">
              <img src="{% static '/newsapp/images/insta.png' %}" alt="">
              </a>
            </div>
          </div>
          <div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
            </p>
          </div>
        </div>
      </section>
      <script type="text/javascript" src="{% static '/newsapp/js/jquery-3.4.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static '/newsapp/js/bootstrap.js' %}"></script>
    </footer>
  </body>
</html>

newsapp/templates/newsapp/advert.html
<!DOCTYPE html>
<html lang="en">
</html>

newsapp/templates/newsapp/author.html
{% extends 'newsapp/base.html' %}
{% block content %}
{% load static %}
{% load newsapp_extras %}
<main>
  <section class="news_section layout_padding">
    <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <div class="d-flex flex-column align-items-end">
          <div class="custom_heading-container">
            <div class="author-image">
              <img src="{{ author.image.url }}" alt="">
            </div>
            <div>
              <h2>
                Articles by {{ author_name_surname }}
              </h2>
            </div>
          </div>
        </div>
        <div class="row">
          {% for article in author_articles %}
          <div class="col-sm-4">
            <div class="box">
              <div class="img-box full-image">
                <a href="{% url 'newsapp:detail' article.id %}">
                <img alt="" src="{{ article.image.url }}" >
                </a>
              </div>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="box">
              <div class="detail-box">
                <h3>
                  <a href="{% url 'newsapp:detail' article.id %}">
                  {{ article.headline }}
                  </a>
                </h3>
                <p>Published: {{ article.pub_date|myDate }}</p>
                <p>{{ article.article_text | truncatechars:200 }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-sm-3">
        <div class="d-flex flex-column align-items-end">
          <div class="custom_heading-container">
            <h2>
              May also interest you
            </h2>
          </div>
        </div>
        <div class="row">
          {% for article in recently_added_article_list %}
          <div class="col-sm-12">
            <div class="box">
              <div class="img-box full-image">
                <a href="{% url 'newsapp:detail' article.id %}">
                <img alt="" src="{{ article.image.url }}" >
                </a>
              </div>
              <div class="detail-box">
                <p>{{ article.pub_date|myDate }}</p>
                <h3>
                  <a href="{% url 'newsapp:detail' article.id %}">
                  {{ article.headline }}
                  </a>
                </h3>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

newsapp/templates/newsapp/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  {% load newsapp_extras %}
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>News Portal</title>
    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'newsapp/css/bootstrap.css' %}" />
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!-- <link href="static/newsapp/css/style.css" rel="stylesheet" /> -->
    <link href="{% static 'newsapp/css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'newsapp/css/responsive.css' %}" rel="stylesheet" />
  </head>
  <body class="sub_page">
    <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="/newsapp/">
          <img alt="" src="{% static 'newsapp/images/logo.png' %}" >
          <span>
          News Portal
          </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                {% for topic in topic_list %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'newsapp:topic' topic.name %}">{{ topic.name }} </a>
                </li>
                {% endfor %}
              </ul>
            </div>
        </nav>
        </div>
    </header>
    <!-- end header section -->
    </div>
    <!-- news section -->
    {% block content %}
    {% endblock %}
    <footer>
      <section class="info_section layout_padding">
        <div class="container">
          <div class="info_social">
            <div>
              <a href="">
              <img alt="" src="{% static '/newsapp/images/fb.png' %}" >
              </a>
            </div>
            <div>
              <a href="">
              <img alt="" src="{% static '/newsapp/images/twitter-2.png' %}" >
              <!-- TODO: change for X icon -->
              </a>
            </div>
            <div>
              <a href="">
              <img alt="" src="{% static '/newsapp/images/linkedin.png' %}" >
              </a>
            </div>
            <div>
              <a href="">
              <img alt="" src="{% static '/newsapp/images/insta.png' %}" >
              </a>
            </div>
          </div>
          <div>
            <!-- TODO: add same categories as header plus subcategories -->
            <p>
              <!-- TODO: make list -->
              Terms of Use
Privacy Policy
Manage Cookies+
Ad Choices
Accessibility & CC
About
Newsletters
Transcripts</p>
<p>© {{ current_year }} News Portal Network. All Rights Reserved.
News Portal Sons © {{ current_year_3 }} News Portal Network.
            </p>
            <!-- TODO: add follow us on plus SM icons -->
          </div>
        </div>
      </section>
      <!-- end info_section -->
      <!-- footer section -->
      <!-- <section class="container-fluid footer_section">
        <p>
          &copy; 2019 All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
        </section> -->
      <!-- footer section -->
      <script type="text/javascript" src="{% static '/newsapp/js/jquery-3.4.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static '/newsapp/js/bootstrap.js' %}"></script>
    </footer>
  </body>
</html>

newsapp/templates/newsapp/detail.html
<!-- TODO: replace https://www.code2night.com/ with current article link -->
<!-- TODO: add Pagination (see: https://docs.djangoproject.com/en/4.2/topics/pagination/) -->
{% extends 'newsapp/base.html' %}
{% block content %}
{% load static %}
{% load newsapp_extras %}
<!-- TODO: change article display - article text should be displayed per 3 sentences, not 1 -->
<main>
  <section class="news_section layout_padding">
    <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <div class="d-flex flex-column align-items-end">
          <!-- headline -->
          <div class="custom_heading-container">
            <h2>
              {{ article.headline }}
            </h2>
          </div>
          <!-- image -->
          <div class="box">
            <div class="img-box article-image" >
              <a href="{% url 'newsapp:detail' article.id %}">
              <img alt="" src="{{ article.image.url }}" class="rounded">
              </a>
            </div>
          </div>
          <!-- subtitle -->
          <div class="subtitle-box">
            <div class="author">
              <p>Published: {{ article.pub_date|myDate }}</p>
              <p>Author: <a class="author" href="{% url 'newsapp:author' article.author %}">{{ article.author }}</a></p>
              <p>Tags: <a class="author" href="{% url 'newsapp:topic' article.topic %}">{{ article.topic }}</a></p>
            </div>
            <div class="action-box">
              <div class="action">
                <!-- Whatspp -->
                <a href="https://api.whatsapp.com/send?text=https://www.code2night.com/"  data-action="share/whatsapp/share"
                  target="_blank">
                <img alt="" class="sm-icon" src="{% static 'newsapp/images/whatsapp.png' %}"  >
                </a>
                <!-- Facebook -->
                <a href="">
                <img alt="" class="sm-icon" src="{% static 'newsapp/images/facebook.png' %}"  >
                </a>
                <!-- Twitter -->
                <a href="https://twitter.com/intent/tweet?text=See this article: https://www.code2night.com/" target="_blank">
                <img alt="" class="sm-icon" src="{% static 'newsapp/images/twitter-2.png' %}"  >
                       <!-- TODO: change for X icon -->
       </a>
                <!-- Email -->
                <a class="social-share__share" href="mailto:?subject=NewsPortal%20content%20share&amp;body=Check%20out%20this%20article%3A%0Ahttps%3A%2F%2Fwww.newsportal.com%2F2023%2F09%2F19%2Fchina%2Fchina-germany-xi-dictator-intl-hnk" data-type="email" target="_blank" rel="noopener noreferrer" aria-label="share with email" title="Share with email">
                  <!-- <a href=""> -->
                  <img alt="" class="sm-icon" src="{% static 'newsapp/images/mail.png' %}"  >
                </a>
                <!-- Link -->
                <a href="">
                <img alt="" class="sm-icon" src="{% static 'newsapp/images/link-2.png' %}"  >
                </a>
              </div>
            </div>
          </div>
          <!-- article -->
          {% for sentence in article_text %}
          <p>{{ sentence }}</p>
          {% endfor %}
        </div>
      </div>
      <div class="col-sm-3">
        <div class="d-flex flex-column align-items-end">
          <div class="custom_heading-container">
            <h2>
              May also interest you
            </h2>
          </div>
        </div>
        <div class="row">
          {% for article in recently_added_article_list %}
          <div class="col-sm-12">
            <div class="box">
              <div class="img-box full-image">
                <a href="{% url 'newsapp:detail' article.id %}">
                <img alt="" src="{{ article.image.url }}" >
                </a>
              </div>
              <div class="detail-box">
                <p>{{ article.pub_date|myDate }}</p>
                <h3>
                  <a href="{% url 'newsapp:detail' article.id %}">
                  {{ article.headline }}
                  </a>
                </h3>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

newsapp/templates/newsapp/topic.html
{% extends 'newsapp/base.html' %}
{% block content %}
{% load static %}
{% load newsapp_extras %}
<main>
  <section class="news_section layout_padding">
    <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <div class="d-flex flex-column align-items-end">
          <div class="custom_heading-container">
            <!-- <div class="author-image">
              <img src="{{ topi.image.url }}" alt="">
              </div> -->
            <div>
              <h2>
                More on {{ topic_name }}
              </h2>
            </div>
          </div>
        </div>
        <div class="row">
          {% for article in topic_articles %}
          <div class="col-sm-4">
            <div class="box">
              <div class="img-box full-image">
                <a href="{% url 'newsapp:detail' article.id %}">
                <img alt="" src="{{ article.image.url }}" >
                </a>
              </div>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="box">
              <div class="detail-box">
                <h3>
                  <a href="{% url 'newsapp:detail' article.id %}">
                  {{ article.headline }}
                  </a>
                </h3>
                <p>Published: {{ article.pub_date|myDate }} by <a href="{% url 'newsapp:author' article.author %}">{{ article.author }}</a></p>
                <p>{{ article.article_text | truncatechars:200 }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-sm-3">
        <div class="d-flex flex-column align-items-end">
          <div class="custom_heading-container">
            <h2>
              May also interest you
            </h2>
          </div>
        </div>
        <div class="row">
          {% for article in recently_added_article_list %}
          <div class="col-sm-12">
            <div class="box">
              <div class="img-box full-image">
                <a href="{% url 'newsapp:detail' article.id %}">
                <img alt="" src="{{ article.image.url }}" >
                </a>
              </div>
              <div class="detail-box">
                <p>{{ article.pub_date|myDate }}</p>
                <h3>
                  <a href="{% url 'newsapp:detail' article.id %}">
                  {{ article.headline }}
                  </a>
                </h3>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}